# Generated by Django 4.1.5 on 2023-02-03 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0003_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='subtitle',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hero',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='subtitle',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='title',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Centeredsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField()),
                ('buttonprimarytext', models.CharField(max_length=255)),
                ('buttonprimaryurl', models.CharField(max_length=255)),
                ('buttonsecondarytext', models.CharField(max_length=255)),
                ('buttonsecondaryurl', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
