# Generated by Django 4.1.5 on 2023-02-03 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0005_rename_subtitle_centeredsection_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newssection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_section1', models.CharField(max_length=255)),
                ('subtitle_section1', models.CharField(max_length=255)),
                ('body_section1', models.TextField()),
                ('buttonprimarytext_section1', models.CharField(max_length=255)),
                ('buttonprimaryurl_section1', models.CharField(max_length=255)),
                ('title_section2', models.CharField(max_length=255)),
                ('subtitle_section2', models.CharField(max_length=255)),
                ('body_section2', models.TextField()),
                ('buttonprimarytext_section2', models.CharField(max_length=255)),
                ('buttonprimaryurl_section2', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
