# Generated by Django 4.1.5 on 2023-02-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_newssection'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssection',
            name='imageurl_section1',
            field=models.CharField(default='nothing', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newssection',
            name='imageurl_section2',
            field=models.CharField(default='nothing', max_length=255),
            preserve_default=False,
        ),
    ]
