# Generated by Django 4.1.5 on 2023-02-04 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_test1_author_test2_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test1',
            name='author',
        ),
        migrations.RemoveField(
            model_name='test2',
            name='author',
        ),
    ]
