# Generated by Django 4.1.5 on 2023-02-04 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0013_remove_test1_author_remove_test2_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centeredsection1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('buttonprimarytext', models.CharField(max_length=255)),
                ('buttonprimaryurl', models.CharField(max_length=255)),
                ('buttonsecondarytext', models.CharField(max_length=255)),
                ('buttonsecondaryurl', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hero1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('subtitle', models.TextField()),
                ('buttonprimarytext', models.CharField(max_length=255)),
                ('buttonprimaryurl', models.CharField(max_length=255)),
                ('buttonsecondarytext', models.CharField(max_length=255)),
                ('buttonsecondaryurl', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='test1',
            name='Contents',
        ),
        migrations.RemoveField(
            model_name='test2',
            name='Contents',
        ),
        migrations.DeleteModel(
            name='Contents',
        ),
        migrations.DeleteModel(
            name='test1',
        ),
        migrations.DeleteModel(
            name='test2',
        ),
    ]
