# Generated by Django 4.1.5 on 2023-02-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_centeredsection1_hero1_remove_test1_contents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero1',
            name='author',
        ),
        migrations.AddField(
            model_name='newssection',
            name='title',
            field=models.CharField(default='1', max_length=250),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Centeredsection1',
        ),
        migrations.DeleteModel(
            name='Hero1',
        ),
    ]
