# Generated by Django 4.1.5 on 2023-02-04 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_remove_hero1_author_newssection_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newssection',
            name='title',
        ),
    ]
