# Generated by Django 4.1.5 on 2023-02-04 11:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_remove_newssection_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centeredsection',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='subtitle',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='subtitle',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newssection',
            name='body_section1',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newssection',
            name='body_section2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
