# Generated by Django 4.1.5 on 2023-01-15 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('home', '0004_blogpage_delete_homepage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPage',
            new_name='Homepage',
        ),
    ]
