# Generated by Django 4.1.5 on 2023-01-15 08:42

from django.db import migrations, models
import django.utils.timezone
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contentpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='hero',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='intro',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
