# Generated by Django 4.1.5 on 2023-01-15 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_blogpage_remove_homepage_author_remove_homepage_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPage',
        ),
    ]
