# Generated by Django 4.1.5 on 2023-01-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_body_homepage_bodyheading_homepage_bodytext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='bodyheading',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='headingoneheading',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='headingonetext',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='headingthreeheading',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='headingthreetext',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='headingtwoheading',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='headingtwotext',
            field=models.CharField(max_length=250),
        ),
    ]
