# Generated by Django 4.1.5 on 2023-01-15 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('home', '0009_alter_homepage_bodyheading_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PagePageGalleryImage',
            new_name='GalleryImage',
        ),
    ]
