# Generated by Django 4.1.5 on 2023-01-31 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_organisationpage_projectpage_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='OrganisationPage',
        ),
        migrations.DeleteModel(
            name='ProjectPage',
        ),
    ]
