# Generated by Django 4.1.5 on 2023-01-31 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('home', '0016_organisationpage_projectpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganisationPage',
            new_name='OrganisationsPage',
        ),
    ]
